project_id = "nltsroirhecmteorywrv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public"]

[db]
port = 54322
major_version = 15

[auth]
enabled = true
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"

[functions]
enabled = true
